apiVersion: v1
kind: ConfigMap
metadata:
  name: ts-apparatus-config
  namespace: {{ .Values.namespace }}
  labels:
{{ include "ts-apparatus.labels" . | indent 4 }}
data:
{{- range $key, $value := .Values.env }}
  {{ $key }}: {{ quote $value }}
{{- end }}
