{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ts-apparatus
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
{{- range $k, $v := .Values.ingress.annotations }}
    {{ $k }}: {{ $v | quote }}
{{- end }}
spec:
{{- if and .Values.ingress.tls.enabled .Values.ingress.tls.secretName }}
  tls:
    - secretName: {{ .Values.ingress.tls.secretName }}
      hosts:
{{- range .Values.ingress.tls.hosts }}
        - {{ . }}
{{- end }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ts-apparatus
                port:
                  number: {{ .Values.service.ports.https }}
{{- end }}
