apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "ts-apparatus.name" . }}
    app.kubernetes.io/part-of: {{ include "ts-apparatus.name" . }}
