{{- if and .Values.ingress.tls.enabled .Values.ingress.tls.secretName (not .Values.ingress.tls.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.tls.secretName }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/tls
data:
  tls.crt: REPLACE_WITH_BASE64_CERT
  tls.key: REPLACE_WITH_BASE64_KEY
{{- end }}
